### ISSUE TITLE
Unable to create swap

### ISSUE THREAD

**Issue by skenaja** [versumstudios/report-bugs#111]
**Describe the bug**
Blank screen when you press "create swap" button

**To Reproduce**

1. got to https://versum.xyz/token/versum/35
2. press "Create Swap" on market tab

expected:
- create swap modal
actual:
- blank screen

Console errors:

```
react_devtools_backend.js:3973 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
overrideMethod @ react_devtools_backend.js:3973
te @ main-fe65257a252896e0.js:1
fn @ main-fe65257a252896e0.js:1
value @ main-fe65257a252896e0.js:1
a.componentDidCatch.t.callback @ framework-6599fb29435aee7e.js:1
sa @ framework-6599fb29435aee7e.js:1
gi @ framework-6599fb29435aee7e.js:1
vi @ framework-6599fb29435aee7e.js:1
hi @ framework-6599fb29435aee7e.js:1
(anonymous) @ framework-6599fb29435aee7e.js:1
ks @ framework-6599fb29435aee7e.js:1
rs @ framework-6599fb29435aee7e.js:1
S @ framework-6599fb29435aee7e.js:1
T @ framework-6599fb29435aee7e.js:1
2react_devtools_backend.js:3973 Error rendering page:  Error: Cancel rendering route
    at z (main-fe65257a252896e0.js:1:15184)
    at main-fe65257a252896e0.js:1:15124
    at new Promise (<anonymous>)
    at fe (main-fe65257a252896e0.js:1:15094)
    at main-fe65257a252896e0.js:1:13091
overrideMethod @ react_devtools_backend.js:3973
(anonymous) @ main-fe65257a252896e0.js:1
Promise.catch (async)
fn @ main-fe65257a252896e0.js:1
value @ main-fe65257a252896e0.js:1
a.componentDidCatch.t.callback @ framework-6599fb29435aee7e.js:1
sa @ framework-6599fb29435aee7e.js:1
gi @ framework-6599fb29435aee7e.js:1
vi @ framework-6599fb29435aee7e.js:1
hi @ framework-6599fb29435aee7e.js:1
(anonymous) @ framework-6599fb29435aee7e.js:1
ks @ framework-6599fb29435aee7e.js:1
rs @ framework-6599fb29435aee7e.js:1
S @ framework-6599fb29435aee7e.js:1
T @ framework-6599fb29435aee7e.js:1
react_devtools_backend.js:3973 Error: MISSING_MESSAGE
    at Ke (_app-d148502361671eb4.js:1:2319430)
    at M (9606.efef8590d3ad513d.js:1:6733)
    at ko (framework-6599fb29435aee7e.js:1:62750)
    at ki (framework-6599fb29435aee7e.js:1:120249)
    at ys (framework-6599fb29435aee7e.js:1:109194)
    at gs (framework-6599fb29435aee7e.js:1:109166)
    at rs (framework-6599fb29435aee7e.js:1:104192)
    at S (framework-6599fb29435aee7e.js:1:138287)
    at MessagePort.T (framework-6599fb29435aee7e.js:1:138821)
```

**Comment by andrevenancio** [comment]
thanks for reporting! this has now been solved
