### ISSUE TITLE
`Error: ffmpeg.FS('readFile'` on minting

### ISSUE THREAD

**Issue by kianhossein** [versumstudios/report-bugs#90]
```
{   "stack": "Error: ffmpeg.FS('readFile', 'preview_image_1080w.jpg') error. Check if the path exists
at Object.O [as FS] (https://versum.xyz/_next/static/chunks/976.cca7bfc437274282.js:1:14893)
at https://versum.xyz/_next/static/chunks/529.0a2c2e4767ebfb95.js:1:12151
at l (https://versum.xyz/_next/static/chunks/main-7a639bd74b0f492a.js:1:92495)
at Generator._invoke (https://versum.xyz/_next/static/chunks/main-7a639bd74b0f492a.js:1:92283)
at Generator.P.forEach.e.<computed> [as next] (https://versum.xyz/_next/static/chunks/main-7a639bd74b0f492a.js:1:92918)
at D (https://versum.xyz/_next/static/chunks/529.0a2c2e4767ebfb95.js:1:10123)
at i (https://versum.xyz/_next/static/chunks/529.0a2c2e4767ebfb95.js:1:10326)",  
"message": "An error has occurred whilst trying to encode your token" }
```

**Comment by pichiste** [comment]
Hi @kianhossein, please provide the info requested above, otherwise we can't really help.

**Comment by andrevenancio** [comment]
Is it possible that this path `preview_image_1080w.jpg` was inside a dropbox folder or a folder that displayed the file but the file is stored on the cloud somewhere?

**Comment by kianhossein** [comment]
I finally discovered that somehow the loyalty fee was causing the problem!
I faced the error as i was trying to mint with 20 percent fee but when i
changed it to 10 everything wwnt smoothly!

With regards
Kian Hossein

**Comment by pichiste** [comment]
@kianhossein Did you by chance use a different browser when successfully minting? If so, which browsers? The royalty settings are unrelated to the error.

**Comment by kianhossein** [comment]
I was using the same brower, Chrome.

**Comment by pichiste** [comment]
Ok thank you. Closing this as issue is resolved

**Comment by kianhossein** [comment]
Thank you for being so persuasive
