### ISSUE TITLE
error

### ISSUE THREAD

**Issue by cruacl** [versumstudios/report-bugs#98]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cruacl** [comment]
{
  "stack": "TypeError: Failed to fetch\n    at https://versum.xyz/_next/static/chunks/pages/_app-1fedbf2ee1b4333c.js:1:712890\n    at https://versum.xyz/_next/static/chunks/1631.7e38fd3e20cdc0e3.js:1:15013\n    at l (https://versum.xyz/_next/static/chunks/main-f38ccf3b4cb0b30f.js:1:92495)\n    at Generator._invoke (https://versum.xyz/_next/static/chunks/main-f38ccf3b4cb0b30f.js:1:92283)\n    at Generator.P.forEach.e.<computed> [as next] (https://versum.xyz/_next/static/chunks/main-f38ccf3b4cb0b30f.js:1:92918)\n    at L (https://versum.xyz/_next/static/chunks/1631.7e38fd3e20cdc0e3.js:1:11510)\n    at c (https://versum.xyz/_next/static/chunks/1631.7e38fd3e20cdc0e3.js:1:11713)",
  "message": "An error has occurred whilst trying to upload your token"
}

**Comment by andrevenancio** [comment]
Hi @cruacl is this still happening? If so will you be able to responde to our suggested questions on the first comment? Which device did you use? what token are you trying to mint? anything that could help us repricate this issue.

**Comment by andrevenancio** [comment]
closing due to lack of activity
